[[tables]]
name = "pirates"
[[tables.fields]]
name = "id"
field_type = "numeric"
autoincrement = true
unique = true
indexed = true
[[tables.fields]]
name = "name"
field_type = "text"
indexed = true
fulltext = true
[[tables.fields]]
name = "ship_id"
field_type = "numeric"

[[tables]]
name = "ships"
[[tables.fields]]
name = "ship_id"
name = "id"
field_type = "numeric"
autoincrement = true
unique = true
indexed = true
[[tables.fields]]
name = "name"
field_type = "text"
indexed = true
fulltext = true
[[tables.fields]]
name = "speed"
field_type = "numeric"
