[[tables]]
name = "pirates"
[[tables.fields]]
name = "pirate_id"
unique = true
[[tables.fields]]
name = "name"
[[tables.fields]]
name = "ship_id"

[[tables]]
name = "ships"
[[tables.fields]]
name = "ship_id"
unique = true
[[tables.fields]]
name = "name"
[[tables.fields]]
name = "speed"
