[[tables]]
name = "pirates"
[[tables.fields]]
name = "id"
indexed = true
autoincrement = true
unique = true
[[tables.fields]]
name = "name"
[[tables.fields]]
name = "ship_id"

[[tables]]
name = "ships"
[[tables.fields]]
name = "ship_id"
indexed = true
autoincrement = true
unique = true
[[tables.fields]]
name = "name"
[[tables.fields]]
name = "speed"
